# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
