# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170216_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
